### ISSUE TITLE
获取device后，获取不到服务。

### ISSUE THREAD

**Issue by SocketNet** [lilongweidev/BleDemo#1]
大佬你好，参考了你的demo。和单片机成功建立了低功耗蓝牙连接，但是sendCommand gatt.service方法返回了空的列表。没有服务，就没法通过特征进行通讯。

**Comment by SocketNet** [comment]
`#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
// 服务id
#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
// 特征id
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"
 
 // 数据回调
class MyCallbacks: public BLECharacteristicCallbacks {
    void onWrite(BLECharacteristic *pCharacteristic) {
      std::string value = pCharacteristic->getValue();
 
      if (value.length() > 0) {
        Serial.println("*********");
        Serial.print("New value: ");
        for (int i = 0; i < value.length(); i++)
          Serial.print(value[i]);
 
        Serial.println();
        Serial.println("*********");
      }
    }
};
 
void setup() {
  Serial.begin(115200);
 
  BLEDevice::init("MyESP32");
  BLEServer *pServer = BLEDevice::createServer();
   // 创建服务
  BLEService *pService = pServer->createService(SERVICE_UUID);
  // 基于服务创建特征
  BLECharacteristic *pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_WRITE
                                       );
 
  pCharacteristic->setCallbacks(new MyCallbacks());
 
  pCharacteristic->setValue("Hello World");
  pService->start();
 
  BLEAdvertising *pAdvertising = pServer->getAdvertising();
 // 开启服务
  pAdvertising->start();
}
 
void loop() {
  // put your main code here, to run repeatedly:
  delay(2000);
}`

**Comment by lilongweidev** [comment]
在App中连接成功之后，去发现服务，要在发现服务的回调中去看服务、特性。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lilongweidev/BleDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 中午11:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [lilongweidev/BleDemo] 获取device后，获取不到服务。 (Issue #1)





 
`#include <BLEDevice.h&gt;
 #include <BLEUtils.h&gt;
 #include <BLEServer.h&gt;
 // 服务id
 #define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
 // 特征id
 #define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"
 
// 数据回调
 class MyCallbacks: public BLECharacteristicCallbacks {
 void onWrite(BLECharacteristic *pCharacteristic) {
 std::string value = pCharacteristic-&gt;getValue();
   if (value.length() &gt; 0) {     Serial.println("*********");     Serial.print("New value: ");     for (int i = 0; i < value.length(); i++)       Serial.print(value[i]);     Serial.println();     Serial.println("*********");   } }  
};
 
void setup() {
 Serial.begin(115200);
 
BLEDevice::init("MyESP32");
 BLEServer *pServer = BLEDevice::createServer();
 // 创建服务
 BLEService *pService = pServer-&gt;createService(SERVICE_UUID);
 // 基于服务创建特征
 BLECharacteristic *pCharacteristic = pService-&gt;createCharacteristic(
 CHARACTERISTIC_UUID,
 BLECharacteristic::PROPERTY_READ |
 BLECharacteristic::PROPERTY_WRITE
 );
 
pCharacteristic-&gt;setCallbacks(new MyCallbacks());
 
pCharacteristic-&gt;setValue("Hello World");
 pService-&gt;start();
 
BLEAdvertising *pAdvertising = pServer-&gt;getAdvertising();
 // 开启服务
 pAdvertising-&gt;start();
 }
 
void loop() {
 // put your main code here, to run repeatedly:
 delay(2000);
 }`

**Comment by SocketNet** [comment]
好滴，晚上回去再试试。感谢大佬

________________________________
发件人: chenxi ***@***.***>
发送时间: 2022年10月13日 5:38
收件人: lilongweidev/BleDemo ***@***.***>
抄送: SocketNet ***@***.***>; Author ***@***.***>
主题: Re: [lilongweidev/BleDemo] 获取device后，获取不到服务。 (Issue #1)


在App中连接成功之后，去发现服务，要在发现服务的回调中去看服务、特性。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lilongweidev/BleDemo" ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 中午11:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [lilongweidev/BleDemo] 获取device后，获取不到服务。 (Issue #1)






`#include <BLEDevice.h&gt;
#include <BLEUtils.h&gt;
#include <BLEServer.h&gt;
// 服务id
#define SERVICE_UUID "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
// 特征id
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"

// 数据回调
class MyCallbacks: public BLECharacteristicCallbacks {
void onWrite(BLECharacteristic *pCharacteristic) {
std::string value = pCharacteristic-&gt;getValue();
if (value.length() &gt; 0) { Serial.println("*********"); Serial.print("New value: "); for (int i = 0; i < value.length(); i++) Serial.print(value[i]); Serial.println(); Serial.println("*********"); } }
};

void setup() {
Serial.begin(115200);

BLEDevice::init("MyESP32");
BLEServer *pServer = BLEDevice::createServer();
// 创建服务
BLEService *pService = pServer-&gt;createService(SERVICE_UUID);
// 基于服务创建特征
BLECharacteristic *pCharacteristic = pService-&gt;createCharacteristic(
CHARACTERISTIC_UUID,
BLECharacteristic::PROPERTY_READ |
BLECharacteristic::PROPERTY_WRITE
);

pCharacteristic-&gt;setCallbacks(new MyCallbacks());

pCharacteristic-&gt;setValue("Hello World");
pService-&gt;start();

BLEAdvertising *pAdvertising = pServer-&gt;getAdvertising();
// 开启服务
pAdvertising-&gt;start();
}

void loop() {
// put your main code here, to run repeatedly:
delay(2000);
}`

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

―

**Comment by lilongweidev** [comment]
Close
